### ISSUE TITLE
Use useMemo.

### ISSUE THREAD

**Issue by nimit05** [timsun28/NextJS-Nines-App#163]
const amountOfJokers = [0, 1, 2, 3, 4, 5, 6, 7];

In file Components/GameScreen.tsx , you can use useMemo for the caching , that can optimise the code.

Thanks
Nimit Wadhwa.

**Comment by timsun28** [comment]
Hi Nimit, 

Thank you again for your feedback and support for my app.

Using useMemo with a static array that never changes is not necessary and doesn't provide any meaningful optimization. useMemo is primarily used to memoize the result of expensive calculations or operations that depend on certain dependencies. When the dependencies change, useMemo can help avoid recalculating the result on every render.

In the case of a static array like amountOfJokers that never changes, there's no benefit in using useMemo. React is already efficient at handling constant values, and the use of useMemo in this context would add unnecessary complexity to the code without any real performance improvement.

If you have found differently, please let me know.

Timo
