### ISSUE TITLE
Optimization 

### ISSUE THREAD

**Issue by nimit05** [timsun28/NextJS-Nines-App#164]
export const ScoreView = ({ players, setPlayers, setGameStarted, setGameFinished }: ScoreViewProps) => {
    let totalScores: { [key: string]: number } = {};
    let totalWins: { [key: string]: number } = {};
    let totalJokers: { [key: string]: number } = {};

**This is Heavy calculation and should be optimised by using useMemo**
    players.forEach((player) => {
        const totalScore = calculateTotalScore(player.score);
        totalScores[player.name] = totalScore;
        totalWins[player.name] = Object.values(player.score).filter(
            (score) => typeof score === "string" || score === 0
        ).length;

        // calculate total jokers
        totalJokers[player.name] = Object.values(player.jokers).reduce((sum: number, value: number | string) => {
            if (typeof value === "number") {
                return sum + value;
            }
            return sum;
        }, 0);
    });

**This is Heavy calculation and should be optimised by using useMemo**
    const sortedTotalScore = Object.fromEntries(Object.entries(totalScores).sort(([, a], [, b]) => a - b));
    
    
    
    In the file Components/ScoreView.tsx , Calculations must be cached using useMemo hook , so that it does not recalculate every time the component renders.
    
    Thanks
    Nimit Wadhwa

**Comment by timsun28** [comment]
Hi Nimit, 

Thank you for your feedback and support, 

Because this function is only calculated once, it's not really necessary to use useMemo because it is only calculated on the final page. 

Have you tried out the app itself for keeping track of the game Nines? 

Thank you,
Timo
